version: "3.8"
#docker-compose up -d
services:
  accounts-mongodb:
    image: mongo
    restart: unless-stopped
    command: mongod --port $PORT_ACCOUNTS_MONGODB --quiet --logpath /dev/null
    ports:
      - $PORT_ACCOUNTS_MONGODB:$PORT_ACCOUNTS_MONGODB
    volumes:
      - accounts:/data/db

  sideprojects-mongodb:
    image: mongo
    restart: unless-stopped
    command: mongod --port $PORT_SIDEPROJECTS_MONGODB --quiet --logpath /dev/null
    ports:
      - $PORT_SIDEPROJECTS_MONGODB:$PORT_SIDEPROJECTS_MONGODB
    volumes:
      - sideprojects:/data/db

  svgbattle-mongodb:
    image: mongo
    restart: unless-stopped
    command: mongod --port $PORT_SVGBATTLE_MONGODB --quiet --logpath /dev/null
    ports:
      - $PORT_SVGBATTLE_MONGODB:$PORT_SVGBATTLE_MONGODB
    volumes:
      - svgbattle:/data/db

volumes:
  accounts:
  sideprojects:
  svgbattle:
